big update, bringing puppet5 compatibility, cmk updates, fixes.

diff --git a/files/check_mk/mk-job b/files/check_mk/mk-job
--- a/files/check_mk/mk-job
+++ b/files/check_mk/mk-job
@@ -1,4 +1,5 @@
 #!/bin/bash
+# mk-job: runs monitored jobs on Linux
 # +------------------------------------------------------------------+
 # |             ____ _               _        __  __ _  __           |
 # |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
@@ -6,7 +7,7 @@
 # |           | |___| | | |  __/ (__|   <    | |  | | . \            |
 # |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
 # |                                                                  |
-# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
+# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
 # +------------------------------------------------------------------+
 #
 # This file is part of Check_MK.
@@ -18,10 +19,12 @@
 # in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
 # out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
 # PARTICULAR PURPOSE. See the  GNU General Public License for more de-
-# ails.  You should have  received  a copy of the  GNU  General Public
+# tails. You should have  received  a copy of the  GNU  General Public
 # License along with GNU Make; see the file  COPYING.  If  not,  write
 # to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
 # Boston, MA 02110-1301 USA.
+
+export MK_VARDIR=/var/lib/check_mk_agent
 
 help() {
     echo "Usage: mk-job IDENT PROGRAM [ARGS...]"
@@ -39,12 +42,18 @@ if [ $# -lt 2 ]; then
     exit 1
 fi
 
-OUTPUT_PATH=/var/lib/check_mk_agent/job
+MYSELF=$(id -nu)
+OUTPUT_PATH=$MK_VARDIR/job/$MYSELF
 IDENT=$1
 shift
 
 if [ ! -d "$OUTPUT_PATH" ]; then
-    mkdir -p "$OUTPUT_PATH"
+    if [ "$MYSELF" = root ] ; then
+        mkdir -p "$OUTPUT_PATH"
+    else
+        echo "ERROR: Missing output directory $OUTPUT_PATH for non-root user '$MYSELF'." >&2
+        exit 1
+    fi
 fi
 
 if ! type $1 >/dev/null 2>&1; then
@@ -53,9 +62,18 @@ if ! type $1 >/dev/null 2>&1; then
     exit 1
 fi
 
-date +"start_time %s" > "$OUTPUT_PATH/.$IDENT.running"
-/usr/bin/time -o "$OUTPUT_PATH/.$IDENT.running" --append \
-              -f "exit_code %x\nreal_time %E\nuser_time %U\nsystem_time %S\nreads %I\nwrites %O\nmax_res_kbytes %M\navg_mem_kbytes %K\ninvol_context_switches %c\nvol_context_switches %w" $@
+date +"start_time %s" > "$OUTPUT_PATH/$IDENT.running" 2>/dev/null
+
+if [ ! -w "$OUTPUT_PATH/$IDENT.running" ] ; then
+  # Looks like we are lacking the permissions to create this file..
+  # In this scenario no mk-job status file is created. We simply execute the command
+  $@
+  exit $?
+fi
+
+
+/usr/bin/time -o "$OUTPUT_PATH/$IDENT.running" --append \
+              -f "exit_code %x\nreal_time %E\nuser_time %U\nsystem_time %S\nreads %I\nwrites %O\nmax_res_kbytes %M\navg_mem_kbytes %K\ninvol_context_switches %c\nvol_context_switches %w" "$@"
 RC=$?
-mv "$OUTPUT_PATH/.$IDENT.running" "$OUTPUT_PATH/$IDENT"
+mv "$OUTPUT_PATH/$IDENT.running" "$OUTPUT_PATH/$IDENT"
 exit $RC
